services:
  database:
    image: postgres:latest
    container_name: photo_db
    ports:
      - "127.0.0.1:5430:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres-data:/var/lib/postgresql
    restart: unless-stopped

volumes:
  postgres-data: {}
