services:
  database:
    image: postgres:latest
    container_name: photo_db
    ports:
      - "127.0.0.1:5430:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: photodb
    volumes:
      - postgres-data:/var/lib/postgresql
    restart: unless-stopped

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: photo_app
  #   ports:
  #     - "0.0.0.0:3000:3000"
  #   environment:
  #     DATABASE_URL: postgresql://postgres:mysecretpassword@database:5432/photodb
  #     NEXTAUTH_URL: http://129.151.213.227:3000
  #     NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
  #   depends_on:
  #     - database
  #   restart: unless-stopped

volumes:
  postgres-data: {}
